import time


print("connecting")
time.sleep(4)
print("............................................................")
time.sleep(4)
print("2010/tcp  open  search")
time.sleep(8)
print("2021/tcp  open  server found")
time.sleep(2)
print("connected...........")
time.sleep(6)
print("............................................................")
time.sleep(2)
print(">>001://SRVI NAME-EBANKINGDB1  : HTTPS://ebankingdb.db.com1")
time.sleep(2)
print(">>002://SRVI NAME-EBANKINGDB2  : HTTPS://ebankingdb1.db.com2")
time.sleep(6)
print(">>003://SRVI NAME-EBANKINGDB3  : HTTPS://ebankingdb2.db.com3")
time.sleep(2)
print("................................100%.........................")
time.sleep(4)
print("BANK INSTITUTION : DEUTDESMXXX")
time.sleep(4)
print("IDENITITY CODE : 211690455630BUE")
time.sleep(4)
print("ACCOUNT NUMBER : 100779429000")
time.sleep(4)
print("AMOUNT : 4,732,428,000.00")